name: update NPM dependencies
description: checks if there are updated to NPM packages, and creates a PR with the updated package*.json files.

inputs:
  base-branch:
    description: the branch used as the base for the dependency update checks
    default: main 
    required: false 
  target-branch:
    description: the branch from which the PR is created 
    default: update-dependencies
    required: false
  working-directory:
    description: the working directory of the project to check for dependency updates 
  gh-token:
    description: authentication token with repository access. must have write access to contents and pull requests
    required: true
  debug:
    description: whether to output messages to the console
    default: "false"
runs:
  using: node20 
  main: index.js