name: cache Node and NPM dependenies
description: this action allows to cache both node and NPM dependencies based on the package-lock.json file

inputs:
    node-version:
        description: nodejs version to use
        default: 20.x
        required: true
    working-dir:
      description: working directory of the application
      default: .
      required: false
    target-env:
      description: '"dev" or "prod". control whether dev or prod are installed'
      default: "dev"
      required: false

outputs:
  installed-deps:
    description: whenter dependencies were installed or not
    value: ${{ steps.cache.outputs.cache-hit != 'true' }}

runs:
    using: composite
    steps:
        - name: setup nodejs version ${{inputs.node-version}}
          uses: actions/setup-node@v3
          with: 
            node-version: ${{inputs.node-version}}
        - name: cache dependencies
          uses: actions/cache@v3
          id: cache
          with: 
            path:  ${{inputs.working-dir}}/node_modules
            key: node-modules-${{inputs.target-env}}-${{ hashFiles(format('{0}/{1}', inputs.working-dir, 'package-lock.json')) }}
        - name: install dependencies
          if: steps.cache.outputs.cache-hit != 'true'
          run: ${{ inputs.target-env == 'dev' && 'npm ci' || 'npm ci --omit=dev'}}
          shell: bash
          working-directory: ${{inputs.working-dir}}