name: 04 - using - actions

on: push

jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest

    # 0. checkout code from repository
    # 1. install app deps
    # 2. run automated tests

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v3
        with: 
          node-version: '20.x'
      - name: install dependancies
        run: npm ci
        working-directory: 04-using-actions/react-app