name: 17 - custom actions - composite
run-name: 17 - custom actions - composite | env - ${{inputs.target-env}}

on: 
    workflow_dispatch:
        inputs:
            target-env: 
                description: which environment to target for dependency installation
                type: choice
                options:
                    - dev
                    - prod

env:
    working-directory: 17-custom-actions/react-app
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run: 
                working-directory: ${{env.working-directory}}
        steps:
            - uses: actions/checkout@v4
            - name: setup node and NPM dependencies
              uses: ./.github/actions/composite-cache-dependencies
              with: 
                node-version: 20.x
                working-dir: ${{env.working-directory}}
                target-env: ${{inputs.target-env}}
            - name: test
              run: npm run test 
            - name: build
              run: npm run build 