name: 18-1 reusable workflows - reusable definition 

on: 
    workflow_call: 
        inputs:
            target-directory:
                type: string
                required: true
        outputs:
            build-status:
                description: the status of the build process 
                value: ${{jobs.deploy.outputs.build-status}}
            url:
                description: the url of the deployed version
                value: ${{jobs.deploy.outputs.url}}
jobs:
    deploy:
        runs-on: ubuntu-latest
        outputs:
            build-status: ${{steps.build.outputs.build-status}}
            url: ${{steps.deploy.outputs.url}}
        steps:
            - name: chekout repo
              uses: actions/checkout@v4 
            - name: build 
              id: build
              run: |
                echo "building using directory ${{inputs.target-directory}}."
                echo "build-status=success" >> "$GITHUB_OUTPUT"
            - name: deploy 
              id: deploy
              run: |
                echo "deploying build artifacts"
                echo "url=https://www.google.com"  >> "$GITHUB_OUTPUT"