name: 19 - 1 -  managing concurrency

on:
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}

jobs:
    ping:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: ping url
              id: ping-url 
              uses: ./.github/actions/docker-ping-url
              with: 
                url: https://www.invalidfdfd.com
                max-trials: 20
                delay: 5