name: 19 - 2 -  managing concurrency

on:
    workflow_dispatch:

jobs:
    ping-with-concurrency:
        runs-on: ubuntu-latest
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
        steps:
            - uses: actions/checkout@v4
            - name: ping url
              id: ping-url 
              uses: ./.github/actions/docker-ping-url
              with: 
                url: https://www.invalidfdfd.com
                max-trials: 20
                delay: 5
    ping-without-concurrency:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: ping url
              id: ping-url-2
              uses: ./.github/actions/docker-ping-url
              with: 
                url: https://www.invalidfdfd.com
                max-trials: 20
                delay: 5