name: 20 - workflow security 

on: 
    pull_request:

jobs:
    unsafe-pr: 
        runs-on: ubuntu-latest
        steps:
            - name: checkout code 
              uses: actions/checkout@v4
            - name: check pr title
              run: |
                echo "title=${{github.event.pull_request.title}}"
                if [[ $title =~ ^feat ]]; then
                    echo "pr is a feature"
                    exit 0
                else
                    echo "pr is not a feature"
                    exit 1
                fi
    safer-pr: 
        runs-on: ubuntu-latest
        steps:
            - name: checkout code 
              uses: actions/checkout@v4
            - name: check pr title
              env: 
                TITLE: ${{github.event.pull_request.title}} 
              run: |
                if [[ $TITLE =~ ^feat ]]; then
                    echo "pr is a feature"
                    exit 0
                else
                    echo "pr is not a feature"
                    exit 1
                fi
    js-safer-pr: 
        runs-on: ubuntu-latest
        steps:
            - name: checkout code 
              uses: actions/checkout@v4
            - name: check pr title
              uses: ./.github/actions/security-safe-input
              with: 
                pr-title: ${{github.event.pull_request.title}}